### ISSUE TITLE
Host images in repo

### ISSUE THREAD

**Issue by ajb** [presidential-innovation-fellows/apps-gov#102]
It isn't technically a security flaw, but it's pretty sketch to hotlink to images on separate domains. Also, mixed content warnings if the logo URLs are not served over `https`.

The images could have a standardized path of `images/logos/{{ slug }}.png`, which would make the code nice and pretty.

**Comment by stroupaloop** [comment]
Agreed, need to migrate to this, carving out a folder location within /assets/img/product_images/ need to start migrating them there and update the README.md to reflect this process change

**Comment by stroupaloop** [comment]
Done bc9d2f6
