### ISSUE TITLE
Suggest changing "GitHub" in footer to "Source Code" or similar

### ISSUE THREAD

**Issue by brittag** [presidential-innovation-fellows/apps-gov#104]
It's great that the footer links to this repository! It could help readers for this link to be phrased as a brief description of the function of the link, such as "Source Code" or "Code Repository and Issue Tracking", instead of "GitHub" (which is vendor-specific and also less direct about the purpose of the link).

**Comment by stroupaloop** [comment]
fixed! 5d19270
