### ISSUE TITLE
seed additional json dummy data

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/apps-gov#11]
some company ideas:
- [ ] Okta
- [ ] Authy
- [ ] HackerOne
- [ ] Stripe
- [ ] Evernote
- [ ] SalesForce
- [ ] Atlassian

we can also do an initial scrape from http://www.digitalgov.gov/resources/negotiated-terms-of-service-agreements/

Meeting with Microsoft team to get their list as well, hopefully AWS and Google Cloud will follow suit.

**Comment by stroupaloop** [comment]
Thanks @michael-balint for helping get some initial placeholder data! A couple of quick things it's missing:
- sector
- employee count
- investors (curious what this looks like for public companies)
- angelist_slug

Also, would it be possible to structure the json in a more readable format? It currently spits it out in one line, would be great if it was a new line for each item since this will be updated by the community.

Things we don't need
- overall_score (what is this?)
- object_type
- pe_ratio
- market_cap
- revenue_estimate (maybe?)
- total_funding (maybe?)
- last_funding_date
- twitter_followers_count
- angellist_followers_count

**Comment by michael-balint** [comment]
@stroupaloop 
- I think `sector` is listed first in `top_keywords`
- `number_of_employees` is the employee count
- `investors` should be populated now
- missing `angelist_slug` - how badly do we need this? the `slug` should be pretty close - do we want a direct link?

**Comment by stroupaloop** [comment]
thanks @michael-balint looks good!

Regarding `sector` it seems like it was something different, for example Slack below:

![image](https://cloud.githubusercontent.com/assets/2424551/13094380/48d91a8e-d4d8-11e5-9c90-f3565e3fbde2.png)

Also, would it be possible to consolidate duplicate investors on your end?

**Comment by stroupaloop** [comment]
I think we're good here now, but need to figure out the full list prior to launch
