### ISSUE TITLE
Denied permission to make a pull request

### ISSUE THREAD

**Issue by anisha** [presidential-innovation-fellows/apps-gov#121]
Hey there, @stroupaloop! I'm trying to add DataFox to the government products listing, but when I try to make a pull request, I get the following error: 

`remote: Permission to presidential-innovation-fellows/apps-gov.git denied to a-nish-a.
fatal: unable to access 'https://github.com/presidential-innovation-fellows/apps-gov/': The requested URL returned error: 403`

I'm on my company's Github account and have linked my datafox.com email with my own Github profile, but am still unable to access. Do you know what might be going wrong? I've tried both over https and ssh, and haven't had authentication problems in the past. I've attached our logo and the json file here.
[datafox.zip](https://github.com/presidential-innovation-fellows/apps-gov/files/293838/datafox.zip)

Thanks for your help!

**Comment by ghost** [comment]
Hi @a-nish-a  Please find attached the link for sending your request for adding your products to apps.gov https://apps.gov/listing.Hope this helps

**Comment by ghost** [comment]
Hi @a-nish-a you can make a pull request from this repo https://github.com/presidential-innovation-fellows/apps-gov-v2

**Comment by anisha** [comment]
Worked great! Thank you :)
