### ISSUE TITLE
search broken?

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/apps-gov#58]
May be my internet or this plane, but something seems to be breaking when I perform a search.

**Comment by mbland** [comment]
Don't forget you have to do a `bundle exec rake install_js_components` and `bundle exec rake build` in your local copy of `mbland/jekyll_pages_api_search` before building your site (until we get the changes committed upstream, or I cut a custom gem). Also, pull the `genericize` branch of `mbland/jekyll_pages_api_search`.

**Comment by stroupaloop** [comment]
nice got it working! @mbland looking forward to the gem!
