### ISSUE TITLE
setup low level analytics in GA

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/apps-gov#64]
- [x] click on a product's contact button
- [x] click on a product's edit button
- [x] click on a product tag
- [x] view a product page
- [x] perform a search (and for what?)

Anything else?

**Comment by adamsfallen** [comment]
Looks good - when you update the repo I'll take a look and close this issue.

**Comment by stroupaloop** [comment]
I almost have everything done. As I wrap up all these last pieces, would love your help resolving the last two bullet points here if you can @adamsfallen Thanks!

**Comment by adamsfallen** [comment]
Okay I can help with them - did you update the repo with the above changes yet?

**Comment by stroupaloop** [comment]
Yep!

On Sunday, March 13, 2016, Adam Bonnifield notifications@github.com wrote:

> Okay I can help with them - did you update the repo with the above changes
> yet?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/presidential-innovation-fellows/apps-gov/issues/64#issuecomment-195963082
> .

## 

Sent while in motion.

**Comment by adamsfallen** [comment]
okay the product page goal is now supported - give me a call and I can advise you on the best way to do the search one (there are a couple options).
